name: slider_button
description: Customizable slider button widget for activating/deactivating some event.
version: 2.1.0
homepage: https://github.com/anirudhsharma392/Slider-Button

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vibration: ^3.1.3
  shimmer: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

